### ISSUE TITLE
Does this work with a CMS?

### ISSUE THREAD

**Issue by skdigital** [cyrilwanner/next-optimized-images#104]
Hi this looks to only work with static images placed in the folder structure, is there anyway that it can dynamically optimize images coming in from a CMS like Contentful?

**Comment by JiRadu** [comment]
I use it with keystone v4.x and it works pretty well

**Comment by skdigital** [comment]
How lol? I am struggling to implement it ...

**Comment by cyrilwanner** [comment]
Hi @skdigital 
As you discovered yourself, it only works with images which are directly located in your frontend project because they get optimized during build time and not run time.

However, when you are using contentful, you can use their image api to do most of the manipulations: https://www.contentful.com/developers/docs/references/images-api/

**Comment by kylemh** [comment]
@cyrilwanner with the advent of `getStaticProps` wouldn't this now be possible?

**Comment by cyrilwanner** [comment]
Not out of the box with the current version, but it is a planned feature for the next major version (https://github.com/cyrilwanner/next-optimized-images/issues/120) and will be supported soon.
