### ISSUE TITLE
Unable to use dynamic size - Module not found error

### ISSUE THREAD

**Issue by KolbySisk** [cyrilwanner/next-optimized-images#117]
I'm attempting to make a reusable Image component. The plan is to give the component the image src and size.

✅This works:
```
require(`./images/${imageName}?webp`)
```

✅This works:
```
require(`./images/${imageName}?webp&size=500`)
```

❌This doesn't:
```
require(`./images/${imageName}?webp&size=${size}`)
```

**Comment by cyrilwanner** [comment]
This is unfortunately not possible due to a limitation in webpack and not this plugin. Webpack needs to generate the images during build time and they don't know which sizes will be requested during run time, so it fails. The dynamic file name works because they scan for all files in the given directory and simply optimize all files in it (even if they are never used).
