### ISSUE TITLE
Is it normal?

### ISSUE THREAD

**Issue by semyou** [cyrilwanner/next-optimized-images#119]
Hi,

In my blog, I do the following:

```
<picture>
   <source srcSet={props.image?require(`../public/static/blogmedia/${props.image}?webp`): emptyImage} alt={props.title}   type="image/webp" />
   <source srcSet={props.image?require(`../public/static/blogmedia/${props.image}`): emptyImage} alt={props.title}   /> 
   <img src={props.image?require(`../public/static/blogmedia/${props.image}`): emptyImage} alt={props.title} className="mx-auto d-block overflow-hidden mw-100 mb-5" />
       </picture>
```

When I build my next application, I see that all images that are contained inside blogmedia have been moved under the _next/static/images with 2 versions: the webp and the jpeg one. However, what is driving me nuts, is that the spare images that are never passed under props.image are also in the _next/static/images with their 2 versions even if they are never passed. Any idea why? Does next-optimized-images execute on all folder even if called only on specific props.images?

**Comment by cyrilwanner** [comment]
Hi @semyou, this is a limitation of webpack. When you use a dynamic require (with a variable), webpack processes all images within that folder because this is done during build-time and webpack does not know which images will be requested during run-time (e.g. it could come from a dynamic api, `props.image` could be anything).
So yes, this behavior is normal and expected when using a dynamic require. If you don't want all images to be processed, you would have to move the ones to process into a separate folder.
