### ISSUE TITLE
When requiring an image path I have to add .default

### ISSUE THREAD

**Issue by jordyvandomselaar** [cyrilwanner/next-optimized-images#145]
When importing an SVG I can require the path just fine

```
src={require("../assets/svg/dij-slash.svg")}
```

But when importing a `jpg`  I have to import it like this:

```
image={require("../assets/img/content/diensten-support.jpg").default}
```

Notice the `.default` at the end. Is this intended?

**Comment by durchanek** [comment]
Found this happening for images that are not inlined, either because they are too large or because ?url is set. Filetype doesn't seem to matter, happening with SVGs too. Quite problematic because the image can break when its file size changes.
Tested in 2.5.8-canary.1

**Comment by calclavia** [comment]
I'm getting the same issue - not sure if it's related to using TypeScript?

**Comment by jordyvandomselaar** [comment]
The issue is definitely as @durchanek described. Ran into the same case yesterday where `.default` was not required when the image got inlined.

**Comment by cyrilwanner** [comment]
Thank you all for the bug report! It should indeed not require the `.default`, otherwise, the automatic inlining for smaller images doesn't really make sense.

I think I was now able to reproduce the error. It appears to happen when you either manually install a newer file-loader version or any other plugin/package installs it.

It should now be fixed and I just published a new version: `2.6.0`
Can you please try it again with this version? Thanks!

**Comment by durchanek** [comment]
@cyrilwanner Working great after the update. Thanks!

**Comment by jordyvandomselaar** [comment]
@cyrilwanner that fixed it. Thanks!

**Comment by l3v1k** [comment]
This isn't fixed issue for me, but I've fixed it by disabling fallback to url-loader through option `inlineImageLimit: -1`. Think there may be issue with **[url-loader's default config](https://webpack.js.org/loaders/url-loader/#esmodule)**?

**Comment by Exelord** [comment]
Confirm. The issue is still there
