### ISSUE TITLE
Public folder not being recognized with absolute imports

### ISSUE THREAD

**Issue by fandy** [cyrilwanner/next-optimized-images#149]
```
<Logo src={require('/branding/logo.svg')} />
```

Does not work, but without the `require` it does (Next.js recognizes the absolute path starting from the `public` root folder). Does the plugin not work with absolute plugins, or does it require some additional config not mentioned in the docs?

@cyrilwanner

**Comment by cyrilwanner** [comment]
Hello,
the `require` in this case just works as any other `require` or `import` statement in your code. You also can't import another js file with an absolute path, since that would start at the root of your file system, so you also can't require an image with an absolute path.
If you are using typescript, you could set up a path alias (e.g. `@public/`) which points to your public folder so you don't have `../../../` etc in your code, but a normal absolute path will not work.
