### ISSUE TITLE
can we force all images to be inlined/downloaded ?

### ISSUE THREAD

**Issue by sandys** [cyrilwanner/next-optimized-images#154]
hi,
we are looking to fix an issue in nextjs 9.3+ 

we are using getStaticProps to generate the static pages. We are using Prismic as the CMS. However, even when we are using static export, it doesnt download the images...it just points to the Prismic url.

We would like to have nextjs download all the images and export them . 

next-optimized-images seems to be the best bet here.

**Comment by cyrilwanner** [comment]
Hi @sandys 
Unfortunately, this is currently not possible because the image optimization is based on webpack loaders and the static site generation/export happens after it has already been processed by webpack.
However, this feature is already planned for the next major version, but it is not ready yet.
