### ISSUE TITLE
[Canary] unable to substitute width inside require statement.

### ISSUE THREAD

**Issue by stevenmunro** [cyrilwanner/next-optimized-images#191]
Please consider the following snippet.

`<source srcSet={require('../public/photos/' + src + '?width=400&height=400')} />`

This is obviously from inside a `<picture>` element, and it works. `src` is the filename. However the following doesn't work.

`<source srcSet={require('../public/photos/' + src + '?width=' + width + '&height=400')}  />`

This is where I have a variable passed as `width` and I'm hoping to have this substituted.

`width` is defined as being `const width = '400'`

But, I get the following error message.

`Unhandled Runtime Error
Error: Cannot find module './20200801_072243.jpg?width=400&height=400'`

I'm not sure how `src` can be substituted, and it would work fine, but not `width`.

I'm scratching my head hard on this one!

**Comment by cyrilwanner** [comment]
This is unfortunately a limitation of webpack.
Webpack is not smart enough to know which values this `width` variable will have, so it fails with this error. The `src` variable works because webpack compiles all files which could possibly match the path. But that does not work with the width variable since that could have all possible numbers and it would end up in generating millions of images which just isn't feasible.
