### ISSUE TITLE
Image from API

### ISSUE THREAD

**Issue by stepanushariara** [cyrilwanner/next-optimized-images#74]
Hi Guys,

I have follow the documentation and working well if my image within my Next.js
But it cannot working when the image come from api (other source).
How to make it working with image url ?

Thanks guys

**Comment by cyrilwanner** [comment]
Hi @stepanushariara 
This is not possible, unfortunately. Since this is only a webpack loader, it can only handle local files (you can also not import remote js files with webpack).

If you are in charge of the API, you can optimize the images in the API (e.g. on upload). If you are using a 3rd party API and they haven't optimized their images, you could also use an image optimization proxy in front of their images.
